### ISSUE TITLE
stuck on (offsets found patching)

### ISSUE THREAD

**Issue by RandomGreenKirb** [PhantomGamers/TellTaleWidescreenPatcher#10] opened 2022-09-10 20:57 UTC
everytime i try to use the program it gets stuck on the first section

**Comment by PhantomGamers** [comment] 2022-09-10 22:19
Which game are you trying to use it with?

I saw someone say on the WSGF discord that the latest version doesn't work with Jurassic Park but version 1.2.3 of the patcher does (https://github.com/PhantomGamers/TellTaleWidescreenPatcher/releases/tag/1.2.3).
I have to fix this at some point but I wanted to rewrite the patcher from scratch when I do (or maybe find some way to utilize [SUWSF](https://github.com/phantomgamers/suwsf) for it)

**Comment by RandomGreenKirb** [comment] 2022-09-11 05:53
i tried it on both sam and max remasters

**Comment by PhantomGamers** [comment] 2022-09-11 09:36
I would still recommend trying either https://github.com/PhantomGamers/TellTaleWidescreenPatcher/releases/tag/1.3.0 or https://github.com/PhantomGamers/TellTaleWidescreenPatcher/releases/tag/1.2.3 as there is likely something wrong with the newest release that makes it not work for some people. I'll have to look into it as I'm not sure what it is then since it definitely works for both of the Sam and Max remasters for me :(

**Comment by RandomGreenKirb** [comment] 2022-09-15 03:18
thanks using an older version helped
but incase i ever get a 16/9 monitor in the future is there a way to remove it?

**Comment by PhantomGamers** [comment] 2022-09-15 03:20
The patcher renames the original exe to the .bak extension, so you can just restore that

**Comment by RandomGreenKirb** [comment] 2022-09-15 04:02
ok but fr
the patch works great
the only issues ive had were relating to cutscenes and ui but overall its perfect

**Comment by PhantomGamers** [comment] 2022-09-24 05:54
reopening cuz this is an issue that needs to be resolved (though I can't currently reproduce it on my end :/)

**Comment by PhantomGamers** [comment] 2022-09-24 06:11
fixed in version 1.6 of the patcher!

**Closed as completed by PhantomGamers** 2022-09-24 06:11 UTC
